#envfile

#[TEST]
TEST_VIPER_CONFIG_BOOL_VALUE=fas2dlse
TEST_VIPER_CONFIG_STRING_VALUE=3 "test 998877"
TEST_VIPER_CONFIG_INT_VALUE=9988q77s e 234
TEST_VIPER_CONFIG_INT32_VALUE=214748e fdf3647
TEST_VIPER_CONFIG_INT64_VALUE=922swdf3720 36854775807
TEST_VIPER_CONFIG_UINT_VALUE=99w887 7343
TEST_VIPER_CONFIG_UINT32_VALUE=429r4 9sd672945
TEST_VIPER_CONFIG_UINT64_VALUE=1844e674f 407 3709551615
TEST_VIPER_CONFIG_FLOAT64_VALUE=99r 8.877
TEST_VIPER_CONFIG_TIME_VALUE=2021-09-1e 5T15:3 1:48.00s0000123Z
TEST_VIPER_CONFIG_DURATION_VALUE=9 me
TEST_VIPER_CONFIG_INTSLICE_VALUE=9 9 8  df8 7 7
TEST_VIPER_CONFIG_STRINGSLICE_VALUE=tessdat1 te3 sft"" 2'' test3
TEST_VIPER_CONFIG_STRINGMAP_VALUE=test1 tef "" st 2 tesast3
TEST_VIPER_CONFIG_STRINGMAPSTRING_VALUE=tes"" t1 tes""t2d test3
TEST_VIPER_CONFIG_STRINGMAPSLICE_VALUE=tes""t1 test2  tes"" t3